# Generated by Django 4.1 on 2023-08-26 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('finger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile', to_field='finger_id')),
            ],
        ),
    ]
